### PR TITLE
feat: Allow React 18 as peer dependency

### PR DESCRIPTION
**Pull request by Rassell**
Update peerDependency for made it compatible with react 18

friendly ping @aaronshaf @tremby

All tests pass:
image

### CODE REVIEW

**Comment by Rassell** [comment]
@aaronshaf many thanks for the merge, could you please make a new release?

**Comment by therealjmj** [comment]
+1 :)

**Comment by ghost** [comment]
👍 here too, the NPM release is missing

**Comment by henriquejensen** [comment]
The NPM release is still missing for those who want to use the latest version you can change your package.json like this
```
"react-toggle": "https://github.com/aaronshaf/react-toggle",
```

**Comment by aaronshaf** [comment]
I just pushed 4.1.3

**Pull request merged**
