### PR TITLE
Changes the CSS to better support the disabled state. 

### PR DESCRIPTION
**Pull request by ihenshaw**
- The cursor is not changed when disabled. 
- The background does not transistion to black when disabled. 
- The box-shadow does not appear around the thumb when the component is :active, but disabled

### CODE REVIEW

**Review by ahstro — CHANGES_REQUESTED** [review]
This is looking good, but I'd like it if you could fix two things before I merge it:
1. Could you also make sure that the `background-color` is not changed when hovering a checked toggle button?
2. Could you format your commit message, so that the first line is <=50 characters?

You can achieve both of this by first editing the code, and then running `git commit --amend` and editing the commit message, then you'll have to `git push --force` to your branch.

Thank you!

**Comment by ihenshaw** [comment]
This should now be done. Can't believe I missed that.

**Comment by ahstro** [comment]
Looks a lot better, thanks! Could you also squash the commits with a `git rebase --interactive HEAD^^` and using `fixup` on ee2f661? :)

**Comment by ihenshaw** [comment]
hmmm, that looked ok using `git log` until I pushed it back, it seems to have remerged with master, so now I have 4 commits...

`fixup` is a new one on me, any advice?

Sorry to be a pain.

**Comment by ahstro** [comment]
No worries, my first rebases were a mess too :)

Okay, so let's go through this step by step:

First off, you need to start an interactive rebase. This is done by using the following command: `git rebase --interactive c4843d121e9ac26249524c0fb561e595b451f28f`
I chose `c4843d121e9ac26249524c0fb561e595b451f28f` as the commit because it was the parent of the first commit in this PR.

The previous command opens the following snippet in your configured text editor:

```
pick 35566cb Changes the CSS to better support the disabled state. * The cursor is not changed when disabled. * The background does not transition when disabled. * The box-shadow does not appear around the thumb when the component is :active, but disabled
pick 3cc4d5f Changes the CSS to better support the disabled state. * The cursor is not changed when disabled. * The background does not transition when disabled. * The box-shadow does not appear around the thumb when the component is :active, but disabled
pick ee2f661 no background transition when checked and disabled
```

What you want to do is change `pick` to `fixup` for all but the top commit. It'll look like this:

```
pick 35566cb Changes the CSS to better support the disabled state. * The cursor is not changed when disabled. * The background does not transition when disabled. * The box-shadow does not appear around the thumb when the component is :active, but disabled
fixup 3cc4d5f Changes the CSS to better support the disabled state. * The cursor is not changed when disabled. * The background does not transition when disabled. * The box-shadow does not appear around the thumb when the component is :active, but disabled
fixup ee2f661 no background transition when checked and disabled
```

After this, save and exit the file, so that `git rebase` can finish.

You'll see a message saying something along these lines:

```
[detached HEAD 905b71a] Changes the CSS to better support the disabled state. * The cursor is not changed when disabled. * The background does not transition when disabled. * The box-shadow does not appear around the thumb when the component is :active, but disabled
 Author: ian <ian@thehenshaws.net>
 Date: Fri Sep 23 11:04:09 2016 +0100
 1 file changed, 4 insertions(+), 3 deletions(-)
Successfully rebased and updated refs/heads/master.
```

and if you run `git status`, it'll let you know that your local and remote branches have diverged. 

```
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 4 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working tree clean
```

Usually, this means trouble, but since your remote branch is incorrect, this is fine.
`git status` also tells you to run `git pull`. **Don't do this!** This is probably where it went wrong last time (?), since this will merge your remote branch with your local one, creating a bunch of unwanted commits.

This leads us to the last step. Instead of running `git pull`, we want to push our new, fixed branch to the remote. Since we don't want the old commits to remain, we can't just `git push`, as this will create a merge commit and keep your old commits (come to think of it, _this_ is probably where it went wrong last time?). So, instead of a regular `git push`, we are going to use `git push --force`, or more explicitly `git push --force origin master`, where `origin` is the remote you want to push to, and `master` is the branch. (I'm pretty sure you don't have to be that explicit, but I prefer it since I won't accidentally push anything if I'm on the wrong branch or something similar.)

After that, we should be good to go. Feel free to experiment, and if anything goes wrong, I've got your branch locally, so don't fret if you accidentally destroy things (we might even get to explore `git reflog`).

Sorry about the essay. Hope it helps. Let me know if anything was unclear. Thank you :)

**Comment by ihenshaw** [comment]
Thanks for the help! that seemed to do the trick.

if I recall correct (and I may not, it was yesterday), when I tried to `push`, it moaned about being out of date, so as if on autopilot, I did a `git pull`. I'm guessing I probably forgot to use `--force` and at that point it went bad.

Anyway, hopefully that'll do it. Thank you for the git lesson! Great explanation.

**Review by ahstro — APPROVED** [review]

**Comment by ahstro** [comment]
So you got all the hard parts and and made a small mistake. Sucks when that happens :)

Looks great now though. Thank you!

**Pull request merged**
