### PR TITLE
Use newer React and JS features

### PR DESCRIPTION
**Pull request by ahstro**
This uses some newer features, like stateless functions for the Check and X, and ES6 class syntax for the main component.

It also uses the `static` keyword from `stage-2` presets as a way of declaring static variables on classes, but I added `stage-0` presets as a dependency because I like being able to use all of JS. This feels like it's a bit of a controversial subject though, so if you're unwilling to add stage-0, or any stage presets, to the project, that's completely fine, I'll just use the old syntax for the statics.

### CODE REVIEW

**Comment by aaronshaf** [comment]
I'd recommend against `stage-0` and stick to syntax that eslint can safely understand.

**Comment by ahstro** [comment]
Fair enough :)

**Comment by ahstro** [comment]
If you're ok with this, check #62 before merging. :)

I hope I'm not being to forward with all these changes btw; let me know if I am.

**Comment by aaronshaf** [comment]
@ahstro You're awesome!

**Pull request merged**
