### PR TITLE
update to componentDidUpdate instead of will receive props

### PR DESCRIPTION
**Pull request by kelly-tock**
removed deprecated `willReceiveProps` and switched to `didUpdate`

ran prettier.

### CODE REVIEW

**Comment by kelly-tock** [comment]
is this repo active?

**Comment by pkibbey** [comment]
Good question. It's a really useful component, so I hope that this stays updated.

**Comment by kelly-tock** [comment]
I may have to fork it, will post here if so.

**Comment by aaronshaf** [comment]
@kelly-tock, thanks for the PR. I added you as a collaborator.

**Comment by kelly-tock** [comment]
awesome!

**Comment by kelly-tock** [comment]
when do you think you'll publish a new version to npm?

**Comment by aaronshaf** [comment]
I just did so now. Do you have an npm user account?

**Comment by kelly-tock** [comment]
yes, I do. I see you bumped the version. did you want me to publish it?  not seeing update on npm landing page for this module.

**Comment by aaronshaf** [comment]
The CLI says 4.1.1 is published, but it's not updated on https://www.npmjs.com/package/react-toggle yet.

**Comment by kelly-tock** [comment]
coolio, yeah sometimes it takes a bit!

**Comment by JackHowa** [comment]
Nice -- it's working for me! Thanks

**Pull request merged**
