### PR TITLE
adding 'disabled' and 'hasFocus' to propTypes; add documentation for props to README.md

### PR DESCRIPTION
**Pull request by rovolution**
To Whomever It May Concern,

First wanted to start off by saying thank you for creating this awesome component!

This PR addresses the following:
- Adds `disabled` and `hasFocus` to propTypes
- Adds documentation for the props to the README document

Let me know if you have any questions/comments.

Thanks!
- Rohit K

### CODE REVIEW

**Comment by rovolution** [comment]
@aaronshaf have you had a chance to check this out? thanks!

**Comment by BDiehr** [comment]
Hi @rovolution - I'd love to merge this if you just remove the file changes to `index.js`. I'm guessing you had other changes in your local repositories to add in those prop types to `index.es6.js` (which I also plan on adding) but we'll take care of that in a separate PR.

**Comment by rovolution** [comment]
whoa totally forgot about this PR! yea for sure let me remove the index.js changes

**Comment by rovolution** [comment]
@BDiehr went ahead and made the changes

**Comment by BDiehr** [comment]
merged! Thanks

**Pull request merged**
