### PR TITLE
Clean up project file structure

### LINKED ISSUE #51: Move example gh-pages to docs folder on master branch

### LINKED ISSUE #58: Change file structure
As it is now, the structure of this project feels a bit chaotic, with almost everything living in the root.
I would like to move things into subdirectoris, so that we have a file structure that looks more like this:

```
src/
  x.js
  check.js
  index.js
  index.html
  style.css
dist/
  bundle.js
  index.html
  style.css
docs/
  index.html
  style.css
LICENSE
README.md
package.json
webpack.config.js
.gitignore
.npmignore
```

Now, I'm not particularly familiar with all files in the project yet, but you (hopefully) get the gist of it :)
Basically, we would have everything that will be compiled into the module in `src`, the compiled bundle in `build` (this is what npm and `docs` will use), `docs` will contain what is now split between the `examples` subdirectory and the `gh-pages` branch - i.e., the documentation where people can see the module in action and what people can use to test it out when developing.

If this sounds okay, I can get on it (after merging some PRs so they don't have to rebase), otherwise, just close this. @aaronshaf

### PR DESCRIPTION
**Pull request by ahstro**
Clean up the project by separating source, distribution, and documentation files into their respective subdirectories.
Change the build and development processes accordingly.

This also moves the examples page to `/docs`, which renders the `gh-pages` branch superflous.

@aaronshaf So, this is quite a big change, so I didn't want to push it. I've tried running the dev server and building, and it looks good, but would you mind taking a second look before merging?

Closes #58 
Closes #51

### CODE REVIEW

**Review by aaronshaf — APPROVED** [review]

**Comment by aaronshaf** [comment]
We need to make sure that users aren't needlessly importing another version of React they don't use. This is why I didn't use webpack for `npm run build` previously

**Comment by aaronshaf** [comment]
See example:

https://github.com/nmn/react-timeago/blob/master/package.json#L8

They don't use webpack for public consumption. I recommend that we follow suit and only use webpack for /docs.

**Comment by ahstro** [comment]
Okay, that makes sense. I'll fix it

**Comment by ahstro** [comment]
Okay, this should be a better solution. Tried it out with `npm link`, and seems to work fine. :)

**Pull request merged**
